name: Daily Commit

on:
  schedule:
    # Runs daily at 07:30 UTC (you can change time if needed)
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update with 24ds3000105@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily update on $(date)"
          git push


